server:
  port: 8085
  error:
    include-stacktrace: never

spring:
  application:
    name: technician-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: hardik.khurana@octalsoftware.com
    password: sjnh jrrq mzvt fgyl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect



  datasource:
      url: jdbc:mysql://localhost:3306/fsm-technician
      username: root
      password: octal#321
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialize: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  fetch-registry: true
  instance:
    prefer-ip-address: true
#    instance-id: ${EUREKA_INSTANCE_IP}:${spring.application.name}:${server.port}
#    ip-address: ${EUREKA_INSTANCE_IP:${spring.cloud.client.ip-address}}



forgot.password.time.in.second: 60
forgot.password.otp.resend.count: 3
user.activation.link.url: http://12.com:7070/?token=<token>
user.forget.password.link: http://65.72/reset-password/<token>
springdoc:
  api-docs.path : /api-docs
  swagger-ui.path : /swagger-ui.html
